package:
    name: 'occupationcoder'
    version: '1.0.0'


requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - pandas >=2.2.0
        - dask >=2025.5.0
        - scikit-learn >=1.7.0
        - nltk >=3.9.0
        - fuzzywuzzy >=0.18.0
        - numpy >=2.3.0
        - pyarrow >=20.0.0
source:
  path: ../

about:
    license: 'Apache2'
    summary : 'A tool to use job text, such as job description, to assign standard occupational classification codes. '
    home : 'https://github.com/aeturrell/occupationcoder'